// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrpgpzsfuixntjoznwgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycGdwenNmdWl4bnRqb3pud2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODA4ODksImV4cCI6MjA2NjQ1Njg4OX0.KPnZL4gzlQSHUKNWZB2rRkANxCShSiFcxZ6SbrQQhuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);